# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jeffrey Moro
tagline:          'circuits & dust'
description:      'circuits & dust'
url:              https://jeffreymoro.com

paginate:         5
paginate_path: 	  blog/page:num

# Sass settings
sass:
  sass_dir: public/css/_scss
  style: compressed

# Full URL for indexing
url: https://jeffreymoro.com

# Pagination
plugins: [jekyll-paginate]

# Markdown
kramdown:
  smart_quotes: ["lsquo", "rsquo", "ldquo", "rdquo"]
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1      start_line: 1

# GitHub Integration
repository: jeffreymoro/jeffreymoro-dot-com